### ISSUE TITLE
[CRASH] Crashing on Startup

### ISSUE THREAD

**Issue by Axisiser** [opekope2/OptiGUI#106]
### Loader and its version

0.16.0-1.20.1

### OptiGUI version

2.1.7

### Steps to reproduce

Adding some mods like Cobblemon and Resourcepacks.

### Game logs

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-07-25 00:51:30
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'optigui'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'optigui'
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.UnsupportedOperationException: Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: class opekope2.optigui.internal.InitializerKt
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:310)
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:109)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
	at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.kt:62)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
Mixins in Stacktrace: None found

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24060.7 (47d4bdd9064bc68e82ed85dd3a432e84e907a9be):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.4123 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.4123 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fastprox.dll:WMI Custom Marshaller:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna3454644880750820508.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		opus4j.dll
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.19041.4529 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		wbemcomn.dll:WMI:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		wbemprox.dll:WMI:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		wbemsvc.dll:WMI:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		win32u.dll:Win32u:10.0.19041.4529 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		com.jozufozu.flywheel.mixin.ClientMainMixin (flywheel.mixins.json)
		dev.kir.cubeswithoutborders.client.mixin.MainMixin (cubes-without-borders.mixins.json)
		link.infra.screenshotclipboard.common.mixin.AWTHackMixin (screenshotclipboard-common.mixins.json)

-- Modpack Branding --
Details:
	Modpack: 

-- Cobblemon --
Details:
	Version: 1.5.2
	Is Snapshot: false
	Git Commit: df8f078 (https://gitlab.com/cable-mc/cobblemon/-/commit/df8f078d13702ab9a000438910b822ceffbb2248)
	Branch: HEAD

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 381064320 bytes (363 MiB) / 943718400 bytes (900 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7800X3D 8-Core Processor           
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.45.0.0
	Graphics card #1 name: NVIDIA GeForce RTX 3080
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2206
	Graphics card #1 versionInfo: DriverVersion=32.0.15.5612
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 6.00
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 6.00
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 43157.89
	Virtual memory used (MB): 16641.29
	Swap memory total (MB): 10752.00
	Swap memory used (MB): 729.77
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8096m -Xms256m
	Fabric Mods: 
		additional_rpg_jewelry: Additional RPG Jewelry 1.0.3
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		advancementplaques: Advancement Plaques 1.4.11
		ambientenvironment: Ambient Environment 11.0.0.1
		animatica: Animatica 0.6.1+1.20.4
		animation_overhaul: Animation Overhaul 1.3.1
		appleskin: AppleSkin 2.5.1+mc1.20
		appli: Appli 1.2.1-1.20
		apugli: Apugli 2.10.2+1.20.1-fabric
		archers: Archers (RPG Series) 1.2.5+1.20.1
		architectury: Architectury 9.2.14
		artifacts: Artifacts 9.5.12
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.4
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		attributefix: AttributeFix 21.0.4
		azurelib: AzureLib 2.0.31
		azurelibarmor: AzureLib Armor 2.0.6
		badoptimizations: BadOptimizations 2.1.4
		balm-fabric: Balm 7.3.6
			kuma_api: KumaAPI 20.1.8
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		berserker-rpg: Berserker Class Mod 1.0.8
		bettercombat: Better Combat 1.8.5+1.20.1
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
			org_reflections_reflections: reflections 0.10.2
		betterend: Better End 4.0.11
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterstats: Better Statistics Screen 3.12.4+fabric-1.20.1
		bettertaskbar: Better Taskbar 1.7.0
		betterthirdperson: Better Third Person 1.9.0
		bhmenu: BHMenu-Fabric 2.4.1
		bobby: Bobby 5.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 20.2.13
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.5-1.20.1
			maelstrom_library: Maelstrom Library 1.6.1-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		brandedlogs: Branded Logs 2.0.3
		brb: Better Recipe Book 1.10.0+1.20.0-1
		capes: Capes 1.5.2+1.20
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chat_heads: Chat Heads 0.12.7
		cherishedworlds: Cherished Worlds 6.1.6+1.20.1
		citresewn: CIT Resewn 1.1.5+1.20.1
			citresewn-defaults: CIT Resewn: Defaults 1.1.5+1.20.1
		cleanview: CleanView 1.20.1-v1-fabric
		cleardespawn: Clear Despawn 1.1.15
		clickthrough: ClickThrough 1.20-fabric0.83.0-0.4.1
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.20
		clienttweaks: Client Tweaks 11.1.0
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		cobblemon: Cobblemon 1.5.2+1.20.1
		cobblemon_capturexp: Cobblemon Capture EXP 1.5-fabric-1.0.1
		cobblemon_chaining: Cobblemon Chaining 1.5-fabric-1.0.1
		cobblemon_counter: Cobblemon Counter 1.5-fabric-1.2.0
		cobblemon_spawn_notification: Cobblemon Spawn Notification 1.5-fabric-1.0.0
		cobblemonridingfabric: Cobblemon Riding Fabric 1.2.4
		cobblemontrainers: CobblemonTrainers 1.1.9+1.5.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			selfdotmodlibs: SelfdotModLibs 2.2.3+1.20.1
		cobblepedia: Cobblepedia 0.6.6
		collective: Collective 7.74
		connectivity: Connectivity Mod 1.20.1-5.6
		continuity: Continuity 3.0.0-beta.5+1.20.1
		controlling: Controlling For Fabric 12.0.2
		craterlib: CraterLib 2.0.1
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_cobblemon: Create: Cobblemon Industrialized 0.4
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		cubes-without-borders: Cubes Without Borders 2.1.1+1.20
		cupboard: cupboard 1.20.1-2.7
```

**Comment by opekope2** [comment]
Which version of Fabric Language Kotlin are you using?

**Comment by Axisiser** [comment]
> Which version of Fabric Language Kotlin are you using?

1.11.0

**Comment by opekope2** [comment]
Cobblemon bundles Kotlin 1.8.20 for some reason instead of depending on FLK or JAR-in-JAR'ing it. This causes serious compatibility issues. Download a matching version of Fabric Language Kotlin (the one with Kotlin 1.8.22 seems to work).
