### ISSUE TITLE
[BUG] It doesn't work with me 

### ISSUE THREAD

**Issue by dop1909** [opekope2/OptiGUI#109]
### Expected Behavior

doesn't work on 1.21

### Actual Behavior

not thing change  when i install it

### Steps To Reproduce

I install the mod and nothing change to my game

### Loader and its version

Fabric Loader 0.16.0

### OptiGUI version

2.3.0-beta.2+1.21

### Behavior difference

- [ ] OptiGUI documentation
- [ ] OptiFine
- [ ] Something you logically expect from OptiGUI
- [X] Doesn't work at all

### Anything else

no

**Comment by opekope2** [comment]
Do you have a [supported resource pack](https://github.com/opekope2/OptiGUI#supported-resource-packs) enabled?

**Comment by dop1909** [comment]
![image](https://github.com/user-attachments/assets/b12d8324-ec68-460c-bddf-fd0e3d6320e7)
I use Colorful containers pack

**Comment by opekope2** [comment]
![OptiGUI with Colourful Containers enable](https://github.com/user-attachments/assets/765a4ec3-c246-4b30-af1b-6b5f3d73ba42)

I don't see the problem, can you explain what doesn't work?

**Comment by MattHopes** [comment]
I have the same problem, I'm using colorful container resourcepack and optigui 2.3.0-beta.2+1.21, but enderchest and others don't have their resourcepack. I get these errors in the logs.

```
[13:59:54] [Render thread/ERROR]: No filter was created for container `minecraft:chest` in `minecraft:optifine/gui/container/chests/chest.properties`, because selector `date=1 2 3 4 5 6 7 8 9 spooktober 11 dec@1-23 dec@27-31` threw an exception
java.lang.RuntimeException: Invalid dates: `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `spooktober`, `11`
	at opekope2.optigui.internal.selector.DateSelector.parseFailed(IndependentSelectors.kt:28) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.selector.AbstractListSelector.createFilter(AbstractListSelector.kt:23) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.createFilters(FilterLoader.kt:150) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.loadFilters(FilterLoader.kt:79) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.reload$lambda$2(FilterLoader.kt:45) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.reload$lambda$3(FilterLoader.kt:45) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
[13:59:54] [Render thread/ERROR]: No filter was created for container `minecraft:trapped_chest` in `minecraft:optifine/gui/container/chests/chest.properties`, because selector `date=1 2 3 4 5 6 7 8 9 spooktober 11 dec@1-23 dec@27-31` threw an exception
java.lang.RuntimeException: Invalid dates: `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `spooktober`, `11`
	at opekope2.optigui.internal.selector.DateSelector.parseFailed(IndependentSelectors.kt:28) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.selector.AbstractListSelector.createFilter(AbstractListSelector.kt:23) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.createFilters(FilterLoader.kt:150) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.loadFilters(FilterLoader.kt:79) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.reload$lambda$2(FilterLoader.kt:45) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at opekope2.optigui.internal.FilterLoader.reload$lambda$3(FilterLoader.kt:45) ~[optigui-2.3.0-beta.2+1.21.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
```

**Comment by dop1909** [comment]
Im using " Colorful Containers " resourcepack and optigui 2.3.0-beta.2+1.21 , the ender chest , large chest doens't get their own gui instead of replacing the normal chest gui ; the shulker box doesn't get their own color gui . Im playing on 1.21 , Lunar client

**Comment by opekope2** [comment]
I clearly messed up `christmas=false`. I don't yet know the shulkers, I'll check on it this weekend.

**Comment by opekope2** [comment]
Upon further inspection, the OptiGUI `date` selector doesn't conform to the wiki.
