### ISSUE TITLE
Chests, Ender Chests, and Shulker box colours are not working (I am using colourful containers -kingybu-)

### ISSUE THREAD

**Issue by loopyspooky** [opekope2/OptiGUI#114]
### Expected Behavior

Its supposed to work with this mod but it isn't

### Actual Behavior

Chests and enderchests have the gui of a barrel and shulkers of the default purple colour

### Steps To Reproduce

Help Please

### Loader and its version

Fabric Loader 0.16.5 (lunar client 1.21.1)

### OptiGUI version

1.21.1

### Behavior difference

- [ ] OptiGUI documentation
- [ ] OptiFine
- [ ] Something you logically expect from OptiGUI
- [X] Doesn't work at all

### Anything else

ASAP please
![DELETE](https://github.com/user-attachments/assets/3bd5408c-feae-4873-b7cc-f6268a6aaa30)
![ME TOO](https://github.com/user-attachments/assets/f420237a-ae84-469e-bf34-0da83f17f864)
![ME](https://github.com/user-attachments/assets/9ec5dca8-eef4-4779-8b20-aa1801514cff)

**Comment by opekope2** [comment]
Seems like a duplicate of #109. I'll check on it this weekend.

**Comment by loopyspooky** [comment]
![me](https://github.com/user-attachments/assets/28d282f3-2bec-4a42-8157-b8a9832c1559)
is this helpful (log)

**Comment by loopyspooky** [comment]
I disabled it from editing ebe still not working

**Comment by loopyspooky** [comment]
Also this might be very helpful: 

```
[11:21:39] [Render thread/INFO]: [STDERR]: java.lang.IllegalStateException: Failed to launch entrypoint opekope2.optigui.registry.ContainerDefaultGuiTextureRegistry
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.CCHRCRIRCOIIHIIOIHRRRCCIHRRHHC.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.md685293$lambda$ichor$fabric$clientInitializer$0$9(SourceFile:4888)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.handler$zke000$ichor$fabric$clientInitializer(SourceFile:4886)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:477)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.redirect$zdo000$lunar$main$minecraft(SourceFile:1117)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.main(SourceFile:239)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.IIIOHCHIOCCOOCRICCHCIHOIRROORR.ROHHCOIHHIHHRIHRICIOOOICOHCOOH(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Failed to instantiate external Entrypoint(client): opekope2.optigui.registry.ContainerDefaultGuiTextureRegistry
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	... 15 more
[11:21:39] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodException: opekope2.optigui.registry.ContainerDefaultGuiTextureRegistry.<init>()
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor0(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	... 17 more
[11:21:39] [Render thread/INFO]: [STDERR]: java.lang.IllegalStateException: Failed to launch entrypoint opekope2.optigui.internal.FilterLoader
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.CCHRCRIRCOIIHIIOIHRRRCCIHRRHHC.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.md685293$lambda$ichor$fabric$clientInitializer$0$9(SourceFile:4888)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.handler$zke000$ichor$fabric$clientInitializer(SourceFile:4886)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:477)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.redirect$zdo000$lunar$main$minecraft(SourceFile:1117)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.main(SourceFile:239)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.IIIOHCHIOCCOOCRICCHCIHOIRROORR.ROHHCOIHHIHHRIHRICIOOOICOHCOOH(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Failed to instantiate external Entrypoint(client): opekope2.optigui.internal.FilterLoader
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	... 15 more
[11:21:39] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodException: opekope2.optigui.internal.FilterLoader.<init>()
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor0(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:39] [Render thread/INFO]: [STDERR]: 	... 17 more
[11:21:40] [Render thread/INFO]: [STDERR]: java.lang.IllegalStateException: Failed to launch entrypoint opekope2.optigui.internal.interaction.InteractionHandler
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.CCHRCRIRCOIIHIIOIHRRRCCIHRRHHC.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.md685293$lambda$ichor$fabric$clientInitializer$0$9(SourceFile:4888)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.handler$zke000$ichor$fabric$clientInitializer(SourceFile:4886)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:477)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.redirect$zdo000$lunar$main$minecraft(SourceFile:1117)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.main(SourceFile:239)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.IIIOHCHIOCCOOCRICCHCIHOIRROORR.ROHHCOIHHIHHRIHRICIOOOICOHCOOH(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Failed to instantiate external Entrypoint(client): opekope2.optigui.internal.interaction.InteractionHandler
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	... 15 more
[11:21:40] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodException: opekope2.optigui.internal.interaction.InteractionHandler.<init>()
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor0(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	... 17 more
[11:21:40] [Render thread/INFO]: [STDERR]: java.lang.IllegalStateException: Failed to launch entrypoint opekope2.optigui.internal.TextureReplacer
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.CCHRCRIRCOIIHIIOIHRRRCCIHRRHHC.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.md685293$lambda$ichor$fabric$clientInitializer$0$9(SourceFile:4888)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.handler$zke000$ichor$fabric$clientInitializer(SourceFile:4886)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:477)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.redirect$zdo000$lunar$main$minecraft(SourceFile:1117)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.main(SourceFile:239)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.IIIOHCHIOCCOOCRICCHCIHOIRROORR.ROHHCOIHHIHHRIHRICIOOOICOHCOOH(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Failed to instantiate external Entrypoint(client): opekope2.optigui.internal.TextureReplacer
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	... 15 more
[11:21:40] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodException: opekope2.optigui.internal.TextureReplacer.<init>()
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor0(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IIIOHCHIOCCOOCRICCHCIHOIRROORR.IIIOHCHIOCCOOCRICCHCIHOIRROORR.COHCRHIOOOHHRHRCCCHHHROCHHIHCO(Unknown Source)
[11:21:40] [Render thread/INFO]: [STDERR]: 	... 17 more
```

**Comment by loopyspooky** [comment]
Full log :

[latest.log](https://github.com/user-attachments/files/17054355/latest.log)

**Comment by opekope2** [comment]
Lunar client is doing something very wrong with the entry points, you should report it to them instead.

**Comment by opekope2** [comment]
OptiGUI had nothing to do with EBE, EMF, or CEM.

**Comment by loopyspooky** [comment]
Could you tell me how to resolve an entry point issue or like help please

**Comment by loopyspooky** [comment]
Or tell me which mod to remove or if I have to put optigui in the overrides folder.

**Comment by opekope2** [comment]
The shulkers don't work, because of how Lunar client executes the entry points. Some entry points crash, some get called, others don't.
Because of this line:
`java.lang.IllegalStateException: Failed to launch entrypoint opekope2.optigui.internal.FilterLoader`
OptiGUI doesn't load any resources.
This is a Lunar client issue.

**Comment by Rigner** [comment]
This issue will be resolved soon as mentioned in https://github.com/opekope2/OptiGUI/issues/121#issuecomment-3451129197
