### ISSUE TITLE
Windows Defender loading issue

### ISSUE THREAD

**Issue by ImNotStable** [opekope2/OptiGUI#57]
### Loader and its version

0.14.21

### OptiGUI version

2.1.2

### Steps to reproduce

I just loaded the mod

### Game logs

```
[01:47:41] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:212) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189) ~[fabric-loader-0.14.21.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\jerem\Documents\Essential Launcher\mods\optigui-2.1.2.jar]: java.io.FileNotFoundException: C:\Users\jerem\Documents\Essential Launcher\mods\optigui-2.1.2.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:212) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189) ~[fabric-loader-0.14.21.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\jerem\Documents\Essential Launcher\mods\optigui-2.1.2.jar]: java.io.FileNotFoundException: C:\Users\jerem\Documents\Essential Launcher\mods\optigui-2.1.2.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:263) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212) ~[fabric-loader-0.14.21.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.io.FileNotFoundException: C:\Users\jerem\Documents\Essential Launcher\mods\optigui-2.1.2.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1312) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:186) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:284) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:253) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212) ~[fabric-loader-0.14.21.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

### Anything else

This is concerning

**Comment by opekope2** [comment]
Please upload it to [VirusTotal](https://www.virustotal.com/) and send a link (or just send a hash of the file if you know how to do it).

**Comment by ImNotStable** [comment]
If I'm being honest the "This is concerning" was a joke, I was more trying to alert you of this. I wasn't sure if you were aware this could happen with the latest version.

**Comment by ImNotStable** [comment]
Also I immediately had the file quarantined and deleted so I can't send you any data on the mod downloaded, I apologize for not keeping that file for that purpose.

**Comment by opekope2** [comment]
I just wanted to check if you downloaded a malicious one, or it got infected.
The three official sources are GitHub, Modrinth, and CurseForge. They are published by the CI. I downloaded them, and their hash matched.
I don't suspect that any of my accounts or keys were leaked.
This seems like Windows Defender hooked into the file open API after a bit of search, I don't know, I use Arch btw. (Please do **NOT** disable Defender)

**Comment by opekope2** [comment]
I don't think I can do anything about the AV. Make sure to only download OptiGUI from the official sources (GitHub, Modrinth, CurseForge, linked on top of README as badges).
